### ISSUE TITLE
Add user Authentication functionality

### ISSUE THREAD

**Issue by uvansh** [uvansh/Library_management_system#1]
Simple library management project with add, update, search, view and delete functionality improving and adding more functionality

**Comment by erickmontalvo** [comment]
Hi uvansh, I just want to clarify---you want to add a way for the user to verify themselves?

**Comment by uvansh** [comment]
> Hi uvansh, I just want to clarify---you want to add a way for the user to verify themselves? 

Yes like I want users and admin seprated login panel, ex users will not be able to delete add and update books they can only borrow and return books while admins can add delete and update details

**Comment by uvansh** [comment]
Completed
